CC = gcc
CFLAGS= -std=c99 -pedantic -Wall -Wextra -g
BIN = ccl.exe
OBJ = pgm.obj matrix.obj main.obj

# vzorové pravidlo pro generování všech objektových souborů
%.o : %.c
        $(CC) $(CFLAGS) -c $<

# Startovací pravidlo - pro přehlednost
all: $(BIN)

# Generování závislostí
# při změně souborů spustíme 'make dep'
dep:
        $(CC) -MM *.c >dep.list

-include dep.list

# závěrečné slinkování
$(BIN): $(OBJFILES)
        $(CC) $(CFLAGS) $(OBJFILES) -o $@