# Project: ccl
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o pgm.o matrix.o node.o
LINKOBJ  = main.o pgm.o matrix.o node.o
LIBS     = -L"D:/programovani/Dev-Cpp/TDM-GCC-64/lib" -L"D:/programovani/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/programovani/Dev-Cpp/TDM-GCC-64/include" -I"D:/programovani/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/programovani/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/programovani/Dev-Cpp/TDM-GCC-64/include" -I"D:/programovani/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/programovani/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/programovani/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ccl.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = D:\programovani\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

pgm.o: pgm.c
	$(CC) -c pgm.c -o pgm.o $(CFLAGS)

matrix.o: matrix.c
	$(CC) -c matrix.c -o matrix.o $(CFLAGS)

node.o: node.c
	$(CC) -c node.c -o node.o $(CFLAGS)
